# Generated by Django 2.0.7 on 2018-09-22 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='conn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('GameName', models.CharField(max_length=50)),
                ('url', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='conn',
            name='gameId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.game'),
        ),
        migrations.AddField(
            model_name='conn',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
