# Generated by Django 2.0.7 on 2018-11-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20180929_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
