# Generated by Django 2.0.7 on 2018-11-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_game_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gamePhoto',
            field=models.ImageField(blank=True, null=True, upload_to='game_photos'),
        ),
    ]
